include: package:very_good_analysis/analysis_options.yaml


analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  strong-mode:
    implicit-casts: true
    implicit-dynamic: true


linter:
  rules:

    lines_longer_than_80_chars: false