name: bloc_infinite_list
description: Serves pre-made infinite list cubit and bloc to reduce boilerplate and provide concrete immutable bloc implementation. 
version: 0.0.6
homepage: https://github.com/Hwan-seok/flutter_infinite_list
issue_tracker: https://github.com/Hwan-seok/flutter_infinite_list/issues


environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  collection: ^1.16.0

  dio: ^4.0.6
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  meta: ^1.7.0


dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  fake_async: ^1.3.0
  json_serializable: ^6.6.1
  test: ^1.22.2
  very_good_analysis: ^3.1.0