name: bloc_infinite_list
description: Serves pre-made infinite list cubit and bloc to reduce boilerplate and provide concrete immutable bloc implementation. 
version: 1.0.0
homepage: https://github.com/Hwan-seok/flutter_infinite_list
issue_tracker: https://github.com/Hwan-seok/flutter_infinite_list/issues


environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  collection: ^1.17.0

  equatable: ^2.0.5
  meta: ^1.8.0


dev_dependencies:
  fake_async: ^1.3.0
  flutter_lints: ^2.0.0
  test: ^1.24.1
  very_good_analysis: ^4.0.0