name: infinite_list_bloc
description: A new Flutter package project.
version: 0.0.1
# homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  collection:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0

  meta: ^1.7.0

  equatable: ^2.0.5

dev_dependencies:
  test:
  flutter_lints: ^2.0.0
